version: '0.0.1'

services:
  api:
    build: .
    container_name: api
    external_links:
      - postgres:postgres
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"

  database:
    image: postgres
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"